//
//  DeveloperPreview.swift
//  AirBnB_beta
//
//  Created by Kostya on 01/08/2024.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Alex Lesli",
            ownerImageUrl: "man_sanFrancisco",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 150,
            latitude: 37.7749,
            longitude: -122.4194,
            imageURLs: ["sanFrancisco_1", "sanFrancisco_2", "sanFrancisco_3", "sanFrancisco_4"],
            address: "123 Main St",
            city: "San Francisco",
            state: "CA",
            title: "Cozy Apartment in SF",
            rating: 4.55,
            features: [.selfCheckin, .superHost],
            amenities: [.wifi, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "John Doe",
            ownerImageUrl: "man_LA",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 120,
            latitude: 34.0522,
            longitude: -118.2437,
            imageURLs: ["la_1", "la_2", "la_3", "la_4"],
            address: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            title: "Modern Loft in LA",
            rating: 4.75,
            features: [.selfCheckin],
            amenities: [.wifi, .kitchen],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Jaden Smith",
            ownerImageUrl: "man_NYC",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 200,
            latitude: 40.7128,
            longitude: -74.0060,
            imageURLs:["nyc_1", "nyc_2", "nyc_3", "nyc_4"],
            address: "789 Broadway",
            city: "New York",
            state: "NY",
            title: "Spacious Condo in NYC",
            rating: 4.85,
            features: [.superHost],
            amenities: [.wifi, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Emily Davis",
            ownerImageUrl: "woman_London",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 90,
            latitude: 51.5074,
            longitude: -0.1278,
            imageURLs: ["london_1", "london_2", "london_3", "london_4"],
            address: "123 Baker St",
            city: "London",
            state: "England",
            title: "Charming Studio in London",
            rating: 4.65,
            features: [.selfCheckin],
            amenities: [.wifi, .kitchen],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Michael Brown",
            ownerImageUrl: "man_paris",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 6,
            pricePerNight: 250,
            latitude: 48.8566,
            longitude: 2.3522,
            imageURLs:["paris_1", "paris_2", "paris_3", "paris_4"],
            address: "456 Champs Elysees",
            city: "Paris",
            state: "France",
            title: "Luxury House in Paris",
            rating: 4.95,
            features: [.selfCheckin, .superHost],
            amenities: [.wifi, .balcony, .kitchen],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Sarah Wilson",
            ownerImageUrl: "woman_tokio",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 3,
            pricePerNight: 130,
            latitude: 35.6895,
            longitude: 139.6917,
            imageURLs: ["tokio_1", "tokio_2", "tokio_3", "tokio_4"],
            address: "789 Shibuya",
            city: "Tokyo",
            state: "Japan",
            title: "Modern Apartment in Tokyo",
            rating: 4.80,
            features: [.selfCheckin],
            amenities: [.wifi, .kitchen, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "David Johnson",
            ownerImageUrl: "man_berlin",
            numberOfBedrooms: 3,
            numberOfBathrooms: 3,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 160,
            latitude: 52.5200,
            longitude: 13.4050,
            imageURLs: ["berlin_1", "berlin_2", "berlin_3", "berlin_4"],
            address: "123 Alexanderplatz",
            city: "Berlin",
            state: "Germany",
            title: "Cozy Apartment in Berlin",
            rating: 4.70,
            features: [.superHost],
            amenities: [.wifi, .balcony],
            type: .townhouse
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Emma Lee",
            ownerImageUrl: "woman_sydney",
            numberOfBedrooms: 4,
            numberOfBathrooms: 2,
            numberOfGuests: 8,
            numberOfBeds: 5,
            pricePerNight: 180,
            latitude: -33.8688,
            longitude: 151.2093,
            imageURLs: ["sydney_1", "sydney_2", "sydney_3", "sydney_4"],
            address: "456 George St",
            city: "Sydney",
            state: "Australia",
            title: "Beautiful House in Sydney",
            rating: 4.60,
            features: [.selfCheckin, .superHost],
            amenities: [.wifi, .kitchen],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Chris Kim",
            ownerImageUrl: "man_seol",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 110,
            latitude: 37.5665,
            longitude: 126.9780,
            imageURLs: ["seol_1", "seol_2", "seol_3", "seol_4"],
            address: "789 Myeongdong",
            city: "Seoul",
            state: "South Korea",
            title: "Modern Condo in Seoul",
            rating: 4.50,
            features: [.selfCheckin],
            amenities: [.wifi, .balcony],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerId: NSUUID().uuidString,
            ownerName: "Olivia Martinez",
            ownerImageUrl: "woman_rome",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 4,
            pricePerNight: 140,
            latitude: 41.9028,
            longitude: 12.4964,
            imageURLs: ["rome_1", "rome_2", "rome_3", "rome_4"],
            address: "123 Via Roma",
            city: "Rome",
            state: "Italy",
            title: "Charming Apartment in Rome",
            rating: 4.65,
            features: [.selfCheckin, .superHost],
            amenities: [.wifi, .kitchen],
            type: .villa
        )
    ]
}
